### ISSUE TITLE
Support <see>, including langword attribute.

### ISSUE THREAD

**Issue by Eagle3386** [loxsmoke/DocXml#16]
I'd like to request support for the aforementioned XML tag as recommended by MS Docs [here](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/recommended-tags#see).

**Comment by loxsmoke** [comment]
You can use \<see\> tag inside of the \<summary\> or \<remarks\> tags. That way the tag would be picked up by DocXml.

**Comment by Eagle3386** [comment]
Thanks for the quick response. However, I'd like to ask two more questions:
1. Do other tags, e. g. `para` support `<see>`, too?
2. Is the `langword` attribute inside the `<see>` tag supported, just as `cref` is? Because that's where my aforementioned link points you to & which I extensively make use of throughout my docs all the time.

**Comment by loxsmoke** [comment]
If you put tag inside of the summary section then it will be returned as text of the Summary property. DocXml does not parse remarks or summary comments.

**Comment by Eagle3386** [comment]
Sorry for the delayed reply.

So, just to be clear:
1. Using `<para> (...) <see cref="System.Type" /> (...)</para>` (with `<para>` itself being mostly contained within `<summary>` tags) won't get parsed?
2. As I _heavily_ use the `langword` attribute, is usage like `<see langword="null" />` support, i. e. does DocXml transform it
a) into a visually distinguishable "block"
b) into a simple "null" word (just like normal text)
c) by simply dropping it
in a method's generated `<summary>` documentation?
3. In your first comment, you said `<see>` inside `<summary>` or even `<remarks>` _is_ supported. However, in your second reply, you stated the opposite by saying:
> If you put tag inside of the summary section then it will be returned as text of the Summary property. DocXml does not parse remarks or summary comments.

What's correct then?

**Comment by loxsmoke** [comment]
1. Yes
2. e. No transformation
3. It would be returned as text inside of Summary or Remarks property value. 

I would recommend you to try the library or just take a look at its' documentation. You would find out answers to your questions much faster. It is a simple library. and it does not do much processing.

**Comment by Eagle3386** [comment]
Sorry for being late again, but I opted for DocFX due to your replies to my previous questions, i. e. no support for `<para>` inside `<summary>`, `<see langword="null" />` & not even `<see>` in general within `<summary>` or `<remarks>` at all.

Though, I admit your library might target simpler usage & my scenario is just way beyond that coverage.
