### ISSUE TITLE
Support for records?

### ISSUE THREAD

**Issue by erikljung** [loxsmoke/DocXml#17]
Hi, looks like a really nice lib! The only thing I can't get to work is getting docs from properties of a `record`. Maybe I'm doing it wrong, please advice me.

```
/// <summary>
/// Retrieving this seems fine.
/// </summary>
/// <param name="SomeInt">Can't touch me.</param>
/// <param name="SomeBool">Can't touch me.</param>
public record Foo( int SomeInt, bool SomeBool );
```

**Comment by loxsmoke** [comment]
mddox and the underlying library DocXml was not updated to handle records. 
I do not have enough time for proper support currently. 
I would welcome a pull request for records.

**Comment by ScarletKuro** [comment]
> Hi, looks like a really nice lib! The only thing I can't get to work is getting docs from properties of a `record`.

necro posting, but:
`record` is just [syntax sugar](https://sharplab.io/#v2:CYLg1APgAgTAjAWAFBQMwAJboMLoN7ID0x6APAM4CuAttQIYBOAngHxEkBKApgC4MCWXAG78AdgHN0PABb9y6cly7V5AMzFcAdO0JlCVWo1Y6yAB0Z1q6UZa4BeAEQBlAPbUuASVE8HLV+/QxHi5xLgZNUkJzBks2JAYuAGMXBmB0AFkmbmTUgAog9H9PbwBKAG5kAF8gA==) for a class. If you want to retrieve the parameter XML comment of the constructor, you can do the following:

```csharp
/// <summary>
/// Retrieving this seems fine.
/// </summary>
/// <param name="SomeInt">Some integer.</param>
record MyRecord(int SomeInt);

var constructor = typeof(MyRecord).GetConstructor(new[] { typeof(int) });
var comment = Reader.GetMethodComments(constructor);
var parameterComment = comment.Parameters[0]; // Will return ("SomeInt", "Some integer.")
```

Now, if you want to get the XML comments for a property:

```csharp
var property = typeof(MyRecord).GetProperty(nameof(MyRecord.SomeInt));
var comment = Reader.GetMemberComments(property); // Summary will have "Some integer."
```

So, I think everything is working out of the box.

**Comment by loxsmoke** [comment]
Thank you for this info. Retrieval works and it makes sense when one knows the internals of the language, 
However, it may be worth implementing something simpler for the records.
