### ISSUE TITLE
Getting parameter types

### ISSUE THREAD

**Issue by TomasaMuller** [loxsmoke/DocXml#19]
Hi,
Does your library also allow getting input types

```
<member name="M:System.IO.File.AppendAllText(System.String,System.String,System.Text.Encoding)">
      <summary>Appends the specified string to the file, creating the file if it does not already exist.</summary>
      <param name="path">The file to append the specified string to.</param>
      <param name="contents">The string to append to the file.</param>
      <param name="encoding">The character encoding to use.</param>
      <exception cref="T:System.ArgumentException">
```

Here I would like to co-relate 
System.String, System.String, System.Text.Encoding to each of the `param` tags that have been used in the documentation.

**Comment by loxsmoke** [comment]
The MethodComment has a Parameters property that contains parameter comments
You can take a look at mddox tool that uses docxml to generate documentation.
