### ISSUE TITLE
Support for Exception tags

### ISSUE THREAD

**Issue by mercurial-moon** [loxsmoke/DocXml#22]
I see that `Exception` tags are unhandled or at least its not mentioned in the documenttation
An example of exception tags

```
      <exception cref="T:System.ArgumentNullException">
              <paramref name="dependencies" /> is <see langword="null" />.- or -A <see cref="T:System.Web.Caching.CacheDependency" /> object in <paramref name="dependencies" /> is <see langword="null" />.</exception>
      <exception cref="T:System.InvalidOperationException">A <see cref="T:System.Web.Caching.CacheDependency" /> object is referenced from more than one <see cref="T:System.Web.Caching.Cache" /> entry.</exception>

```
these typically appear in methods or properties.
would it be too hard to support these?

**Comment by loxsmoke** [comment]
Doable. I do not have time to do it myself but if you would like you can create the pull request and add the list of exceptions to the MethodComments class.

**Comment by mercurial-moon** [comment]
Hi,
I see that `MethodComments` has a list of properties. In which class does one need to do the code for handling the Exception tags.

**Comment by loxsmoke** [comment]
Added Exceptions list to the MethodComments class. 
https://github.com/loxsmoke/DocXml/blob/master/src/DocXml/MethodComments.cs#L42
